// The GPU model table behind the editor's "GPU model" picker.
//
// WHY. Every profile used to report the same GPU: the engine picks one model per host vendor, and
// the only way to change it was two free-text fields that expected the exact WebGL strings — which
// nobody has to hand (customer report CR-5Q7RKX). This table holds the pre-checked models and
// produces both strings in the form the engine prints for each platform, so a profile claims a
// different card by picking a name rather than by typing an ANGLE renderer string from memory.
//
// Two forms per model, because the renderer string names the backend: on Windows the engine prints
// ANGLE's Direct3D11 form with the PCI device id, on Linux its OpenGL form on top of the driver
// (NVIDIA's own, Mesa for Intel and AMD). A Windows persona on a Linux host still claims the
// Direct3D11 form, so the PROFILE's platform picks the form, not the host.
//
// PURE: no React, no `node:` imports, no Electron. The renderer, the coherence rules and the tests
// all import it. The DATA is generated from the corpus-validated r36 engine pool (see below); the
// exported shape and the helpers are the contract, so keep both stable.

export type GpuVendor = "nvidia" | "intel" | "amd";

export interface GpuModel {
  vendor: GpuVendor;
  /** Human label, e.g. "GeForce RTX 4070". */
  name: string;
  /** PCI device id, e.g. 0x2786. */
  deviceId: number;
  /** Dawn spelling, e.g. "lovelace", "gen-12lp", "rdna-2". */
  architecture: string;
  windows: { vendor: string; renderer: string };
  linux: { vendor: string; renderer: string };
}

// GENERATED by SESSION-CONTEXT/186-gpu-model-pool-r36-2026-10-09/gpu_pool.py (`ts`) from the same
// rows as the engine's kGpuPool* tables (r36, persona schema 3): every string here is byte-identical
// to what the engine itself serves for that model. Regenerate rather than edit by hand.
export const GPU_MODELS: readonly GpuModel[] = Object.freeze([
  {
    vendor: "nvidia",
    name: "GeForce GTX 1660 SUPER",
    deviceId: 0x21c4,
    architecture: "turing",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER (0x000021C4) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 2060 SUPER",
    deviceId: 0x1f06,
    architecture: "turing",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER (0x00001F06) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3050",
    deviceId: 0x2507,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 (0x00002507) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3050/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3060",
    deviceId: 0x2504,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002504) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3060/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3060 Ti",
    deviceId: 0x2486,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002486) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3070",
    deviceId: 0x2484,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3070 (LHR)",
    deviceId: 0x2488,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3080",
    deviceId: 0x2206,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 (0x00002206) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3080/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 3090",
    deviceId: 0x2204,
    architecture: "ampere",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 (0x00002204) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3090/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 4060",
    deviceId: 0x2882,
    architecture: "lovelace",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 (0x00002882) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 4060/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 4060 Laptop GPU",
    deviceId: 0x28e0,
    architecture: "lovelace",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU (0x000028E0) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 4070",
    deviceId: 0x2786,
    architecture: "lovelace",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 4070/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 4070 SUPER",
    deviceId: 0x2783,
    architecture: "lovelace",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 SUPER (0x00002783) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 4090",
    deviceId: 0x2684,
    architecture: "lovelace",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4090 (0x00002684) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 4090/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 5060 Ti",
    deviceId: 0x2d04,
    architecture: "blackwell",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 5060 Ti (0x00002D04) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 5060 Ti/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 5070",
    deviceId: 0x2f04,
    architecture: "blackwell",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 5070 (0x00002F04) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 5070/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 5070 Ti",
    deviceId: 0x2c05,
    architecture: "blackwell",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 5070 Ti (0x00002C05) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 5070 Ti/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "nvidia",
    name: "GeForce RTX 5080",
    deviceId: 0x2c02,
    architecture: "blackwell",
    windows: { vendor: "Google Inc. (NVIDIA)", renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 5080 (0x00002C02) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (NVIDIA Corporation)", renderer: "ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 5080/PCIe/SSE2, OpenGL 4.5.0)" },
  },
  {
    vendor: "intel",
    name: "Arc(TM) Pro Graphics",
    deviceId: 0x7d55,
    architecture: "xe-lpg",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) Arc(TM) Pro Graphics (0x00007D55) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) Arc(tm) Graphics (MTL), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "HD Graphics 620",
    deviceId: 0x5921,
    architecture: "gen-9",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) HD Graphics 620 (0x00005921) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) HD Graphics 620 (KBL GT2), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "Iris(R) Xe Graphics (Alder Lake)",
    deviceId: 0x46a6,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x000046A6) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) Graphics (ADL GT2), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "Iris(R) Xe Graphics (Raptor Lake)",
    deviceId: 0xa7a0,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x0000A7A0) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) Graphics (RPL-P), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "Iris(R) Xe Graphics (Tiger Lake)",
    deviceId: 0x9a49,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) Iris(R) Xe Graphics (TGL GT2), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics (Alder Lake)",
    deviceId: 0x4688,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics (0x00004688) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) Graphics (ADL-S GT1), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics (Comet Lake)",
    deviceId: 0x9bc4,
    architecture: "gen-9",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009BC4) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) UHD Graphics (CML GT2), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics (Raptor Lake)",
    deviceId: 0xa788,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics (0x0000A788) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) Graphics (RPL-S), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics (Tiger Lake)",
    deviceId: 0x9a78,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009A78) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) UHD Graphics (TGL GT1), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics 620",
    deviceId: 0x3ea0,
    architecture: "gen-9",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00003EA0) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (WHL GT2), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics 630",
    deviceId: 0x3e9b,
    architecture: "gen-9",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 630 (CFL GT2), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics 730",
    deviceId: 0x4692,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics 730 (0x00004692) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 730 (ADL-S GT1), OpenGL 4.6)" },
  },
  {
    vendor: "intel",
    name: "UHD Graphics 770",
    deviceId: 0xa780,
    architecture: "gen-12lp",
    windows: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Intel(R) UHD Graphics 770 (0x0000A780) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (Intel)", renderer: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 770 (RPL-S), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon 780M Graphics",
    deviceId: 0x1900,
    architecture: "rdna-3",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon 780M Graphics (0x00001900) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon 780M Graphics (radeonsi phoenix LLVM 20.1.2), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon RX 580 2048SP",
    deviceId: 0x6fdf,
    architecture: "gcn-4",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 580 2048SP (0x00006FDF) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 580 2048SP (radeonsi polaris10 ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon RX 6600 XT",
    deviceId: 0x73ff,
    architecture: "rdna-2",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 6600 XT (0x000073FF) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 6600 XT (radeonsi navi23 ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon RX 6700 XT",
    deviceId: 0x73df,
    architecture: "rdna-2",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 6700 XT (0x000073DF) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 6700 XT (radeonsi navi22 ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon RX 7900 GRE",
    deviceId: 0x744c,
    architecture: "rdna-3",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 7900 GRE (0x0000744C) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 7900 GRE (radeonsi navi31 ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon RX 9070 XT",
    deviceId: 0x7550,
    architecture: "rdna-4",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 9070 XT (0x00007550) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon RX 9070 XT (radeonsi gfx1201 ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon(TM) 780M",
    deviceId: 0x15bf,
    architecture: "rdna-3",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon(TM) 780M (0x000015BF) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon 780M (radeonsi phoenix LLVM 20.1.2), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon(TM) 8060S Graphics",
    deviceId: 0x1586,
    architecture: "rdna-3",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon(TM) 8060S Graphics (0x00001586) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon 8060S Graphics (radeonsi gfx1151 ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon(TM) Graphics (Raphael)",
    deviceId: 0x13c0,
    architecture: "rdna-2",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x000013C0) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon Graphics (radeonsi raphael_mendocino ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon(TM) Graphics (Rembrandt)",
    deviceId: 0x164c,
    architecture: "rdna-2",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x0000164C) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon Graphics (radeonsi rembrandt ACO), OpenGL 4.6)" },
  },
  {
    vendor: "amd",
    name: "Radeon(TM) Graphics (Renoir)",
    deviceId: 0x1638,
    architecture: "gcn-5",
    windows: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)" },
    linux: { vendor: "Google Inc. (AMD)", renderer: "ANGLE (AMD, AMD Radeon Graphics (radeonsi renoir ACO), OpenGL 4.6)" },
  },
]);

/** The models of one vendor; every model when the host vendor is unknown. */
export function modelsForVendor(v: GpuVendor | "unknown"): GpuModel[] {
  return v === "unknown" ? [...GPU_MODELS] : GPU_MODELS.filter((m) => m.vendor === v);
}

/**
 * The table entry a stored vendor/renderer pair denotes, in either platform's form, or null when
 * the pair matches none (including a pair with only one half set). Whitespace at the ends is
 * forgiven, because the strings travel through text inputs; nothing else is, because a renderer
 * string that differs by one character is a different claim.
 */
export function findModel(gpuVendor: string | undefined, gpuRenderer: string | undefined): GpuModel | null {
  const v = (gpuVendor ?? "").trim();
  const r = (gpuRenderer ?? "").trim();
  if (!v || !r) return null;
  for (const m of GPU_MODELS) {
    if ((m.windows.vendor === v && m.windows.renderer === r) || (m.linux.vendor === v && m.linux.renderer === r)) return m;
  }
  return null;
}

/** The pair to store for a model on a platform, keyed as the profile stores them. */
export function stringsFor(m: GpuModel, platform: "windows" | "linux"): { gpuVendor: string; gpuRenderer: string } {
  const s = platform === "linux" ? m.linux : m.windows;
  return { gpuVendor: s.vendor, gpuRenderer: s.renderer };
}

/**
 * A model drawn uniformly from the vendor's table (every model when the vendor is unknown), never
 * `exclude` — unless it is the only candidate, in which case there is nothing else to return.
 * `rnd` is Math.random by default; tests inject their own.
 */
export function randomModel(v: GpuVendor | "unknown", exclude?: GpuModel | null, rnd: () => number = Math.random): GpuModel {
  const all = modelsForVendor(v);
  // By identity of the model (vendor + device id), not by object reference, so a structural copy
  // of a table entry excludes it just as well.
  const pool = exclude ? all.filter((m) => !(m.vendor === exclude.vendor && m.deviceId === exclude.deviceId)) : all;
  const from = pool.length ? pool : all;
  if (!from.length) throw new Error(`no GPU models for vendor ${v}`);
  // Clamp: a `rnd` that returns exactly 1 (or more) must not index past the end.
  const i = Math.min(from.length - 1, Math.max(0, Math.floor(rnd() * from.length)));
  return from[i];
}
